{
  description = "vcard-viewer – a VCard viewer built with Rust";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    flake-utils.url = "github:numtide/flake-utils";

    # Provides pre-built Rust toolchains without rustup
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, flake-utils, rust-overlay }:
    flake-utils.lib.eachDefaultSystem (system:
      let
        overlays = [ (import rust-overlay) ];
        pkgs = import nixpkgs { inherit system overlays; };

        # Pin to the stable Rust toolchain; change "stable" to e.g.
        # pkgs.rust-bin.fromRustupToolchainFile ./rust-toolchain.toml
        # to respect a rust-toolchain.toml file.
        rustToolchain = pkgs.rust-bin.stable.latest.default.override {
          extensions = [ "rust-src" "clippy" "rustfmt" ];
        };

        rustPlatform = pkgs.makeRustPlatform {
          cargo = rustToolchain;
          rustc = rustToolchain;
        };

        # Build the package from Cargo.toml / Cargo.lock at the repo root.
        # Use pkgs.lib.cleanSourceWith so that uncommitted changes are included
        # (Nix flake path inputs otherwise only copy git-tracked files).
        src = pkgs.lib.cleanSourceWith {
          src = pkgs.lib.cleanSource ./.;
          filter = path: type:
            !(builtins.elem (baseNameOf path) [ "target" "result" ".direnv" ]);
        };

        vcard-viewer = rustPlatform.buildRustPackage {
          pname = "vcard-viewer";
          version = "0.1.0";
          inherit src;

          # Generated by `nix flake lock`; commit Cargo.lock to the repo.
          cargoLock.lockFile = ./Cargo.lock;

          # Add any native build-time or runtime library dependencies here,
          # e.g. pkgs.openssl pkgs.pkg-config.
          nativeBuildInputs = [ pkgs.pkg-config ];
          buildInputs = [ ];

          meta = {
            description = "A VCard viewer";
            homepage = "https://github.com/youruser/vcard-viewer";
            license = pkgs.lib.licenses.mit;
            mainProgram = "vcard-viewer";
          };
        };
      in
      {
        # `nix build`
        packages.default = vcard-viewer;
        packages.vcard-viewer = vcard-viewer;

        # `nix run`
        apps.default = flake-utils.lib.mkApp { drv = vcard-viewer; };

        # `nix develop`
        devShells.default = pkgs.mkShell {
          inputsFrom = [ vcard-viewer ];
          buildInputs = [
            rustToolchain
            pkgs.rust-analyzer
          ];

          # Teach rust-analyzer where the stdlib source lives.
          RUST_SRC_PATH = "${rustToolchain}/lib/rustlib/src/rust/library";
        };
      }
    );
}
